
import React, { useState, useRef, useEffect } from 'react';
import { GoogleGenAI } from "@google/genai";
import { Upload, RefreshCw, Sparkles, Image as ImageIcon, Wand2, Video, Download, Layers, FileText, Copy, Square, RectangleVertical, RectangleHorizontal, Check, Move, ThumbsUp, ThumbsDown, Linkedin, Smartphone, Eye, Monitor, ShieldCheck, Pencil, Facebook } from 'lucide-react';
import { PrefillData } from '../App';

const VERI_REF_URL = "https://raw.githubusercontent.com/mstaal1974/Brand-Guide-/main/assets/Veri%20Portrait.jpg";
const LOGO_URL = "https://raw.githubusercontent.com/mstaal1974/Brand-Guide-/main/assets/micro%20logo.png";

const OFFICIAL_ASSETS = [
  { url: "https://raw.githubusercontent.com/mstaal1974/Brand-Guide-/main/assets/Veri%20Teaching.jpg", name: "Teaching" },
  { url: "https://raw.githubusercontent.com/mstaal1974/Brand-Guide-/main/assets/Veri%20Thinking.png", name: "Thinking" },
  { url: "https://raw.githubusercontent.com/mstaal1974/Brand-Guide-/main/assets/Veri%20Relaxed.png", name: "Relaxed" },
  { url: "https://raw.githubusercontent.com/mstaal1974/Brand-Guide-/main/assets/veri%20authority.png", name: "Authority" }
];

interface AIGeneratorProps {
    prefillData: PrefillData | null;
}

const AIGenerator: React.FC<AIGeneratorProps> = ({ prefillData }) => {
  // --- STATES ---
  const [activeTab, setActiveTab] = useState<'upload' | 'image-gen' | 'remix' | 'video-gen'>('image-gen');
  const [loading, setLoading] = useState(false);
  const [statusMsg, setStatusMsg] = useState("");
  const [feedbackStatus, setFeedbackStatus] = useState<'none' | 'liked' | 'disliked'>('none');
  const [previewMode, setPreviewMode] = useState<'editor' | 'linkedin' | 'facebook' | 'instagram'>('editor');

  // Content State
  const [image, setImage] = useState<string | null>(null); // Base64 or URL
  const [previewDataUrl, setPreviewDataUrl] = useState<string | null>(null); // Composite Image Data
  const [videoUrl, setVideoUrl] = useState<string | null>(null); // URL for Veo output
  const [remixImage, setRemixImage] = useState<string | null>(null);
  
  // Inputs
  const [prompt, setPrompt] = useState("");
  const [headline, setHeadline] = useState("");
  const [caption, setCaption] = useState("");
  
  // Voice Audit State
  const [voiceScore, setVoiceScore] = useState<number | null>(null);
  const [voiceCritique, setVoiceCritique] = useState<string>("");

  // Configuration
  const [useVeri, setUseVeri] = useState(true);
  const [useColorOverlay, setUseColorOverlay] = useState(true);
  const [showLogo, setShowLogo] = useState(true);
  const [showOverlay, setShowOverlay] = useState(true);
  const [aspectRatio, setAspectRatio] = useState<'1:1' | '3:4' | '16:9'>('1:1');
  
  // Text Tools
  const [textPos, setTextPos] = useState({ x: 0, y: 0 }); // Percentages offset
  const [textAlign, setTextAlign] = useState<'left'|'center'|'right'>('left');
  const [textYAnchor, setTextYAnchor] = useState<'top'|'middle'|'bottom'>('bottom');
  
  // Canvas Ref for Composition
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const remixInputRef = useRef<HTMLInputElement>(null);
  
  // Track auto-generation to prevent loops or double fires
  const hasAutoGenerated = useRef(false);

  // --- EFFECTS ---
  useEffect(() => {
      if (prefillData) {
          // Reset previous state
          setPrompt(prefillData.scenePrompt || "");
          setHeadline(prefillData.headline || "");
          setCaption(prefillData.caption || "");
          
          if (prefillData.mode === 'video') {
              setActiveTab('video-gen');
          } else {
              setActiveTab('image-gen');
          }

          setImage(null);
          setVideoUrl(null);
          setFeedbackStatus('none');
          hasAutoGenerated.current = false; // Reset trigger flag
      }
  }, [prefillData]);
  
  // Auto-generate effect
  useEffect(() => {
    if (prefillData && prompt && !loading && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        // Small timeout to allow state to settle before generation triggers
        setTimeout(() => {
             if (prefillData.mode === 'video') {
                 generateVideo();
             } else if (!image) {
                 generateImage();
             }
        }, 500);
    }
  }, [prefillData, prompt, image, loading]);

  // Redraw canvas whenever visual state changes (Only for Image mode)
  useEffect(() => {
      if (activeTab !== 'video-gen' && image) {
          drawCanvas();
      }
  }, [image, headline, showLogo, showOverlay, textPos, textAlign, textYAnchor, useColorOverlay, aspectRatio]);

  // --- HELPERS ---
  const getStrategy = () => localStorage.getItem('veri_brand_strategy') || "";

  const getUserPreferences = () => {
    const likes = JSON.parse(localStorage.getItem('veri_ai_likes') || "[]");
    const dislikes = JSON.parse(localStorage.getItem('veri_ai_dislikes') || "[]");
    
    if (likes.length === 0 && dislikes.length === 0) return "";
    
    // Format the last 5 entries to save context window
    const recentLikes = likes.slice(-5).join('; ');
    const recentDislikes = dislikes.slice(-5).join('; ');

    return `
    ADAPTIVE LEARNING - USER PREFERENCES:
    The user has provided feedback on previous outputs.
    POSITIVE EXAMPLES (Emulate this style/tone): ${recentLikes}
    NEGATIVE EXAMPLES (Avoid this style/tone): ${recentDislikes}
    `;
  };

  const handleFeedback = (type: 'liked' | 'disliked') => {
    setFeedbackStatus(type);
    
    // Create a snapshot of the current successful/unsuccessful generation settings
    const entry = `Prompt: "${prompt}", Headline: "${headline}", AspectRatio: ${aspectRatio}, UseVeri: ${useVeri}`;
    
    const key = type === 'liked' ? 'veri_ai_likes' : 'veri_ai_dislikes';
    const history = JSON.parse(localStorage.getItem(key) || "[]");
    
    history.push(entry);
    // Keep max 20 items
    if (history.length > 20) history.shift();
    
    localStorage.setItem(key, JSON.stringify(history));
    
    // Optional: Provide feedback to user
    console.log(`Feedback saved: ${type}`);
  };

  const fetchReferenceImage = async (): Promise<string> => {
    const response = await fetch(VERI_REF_URL);
    const blob = await response.blob();
    return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.readAsDataURL(blob);
    });
  };

  const checkApiKey = async () => {
      const win = window as any;
      if (win.aistudio) {
          const hasKey = await win.aistudio.hasSelectedApiKey();
          if (!hasKey) {
              await win.aistudio.openSelectKey();
          }
      }
  };

  const handleApiError = async (e: any, defaultMsg: string) => {
      console.error(e);
      const errStr = (e.message || e.toString()).toLowerCase();
      const isAuthError = 
        errStr.includes("403") || 
        errStr.includes("permission_denied") || 
        errStr.includes("400") || 
        errStr.includes("api_key_invalid") || 
        errStr.includes("api key not valid");

      if (isAuthError) {
          const win = window as any;
          if (win.aistudio) {
              await win.aistudio.openSelectKey();
          } else {
              alert("API Error: Permission denied or Invalid Key. Please check your API key settings.");
          }
      } else {
          alert(defaultMsg);
      }
  };

  // --- CORE LOGIC: DRAWING COMPOSITE ---
  const drawCanvas = () => {
      const canvas = canvasRef.current;
      if (!canvas || !image) return;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      const img = new Image();
      img.crossOrigin = "anonymous";
      img.src = image;
      img.onload = () => {
          // 1. Setup Canvas based on Aspect Ratio
          let targetW = 1080;
          let targetH = 1080;

          if (aspectRatio === '3:4') { targetW = 1080; targetH = 1350; } // Portrait
          if (aspectRatio === '16:9') { targetW = 1920; targetH = 1080; } // Landscape

          canvas.width = targetW;
          canvas.height = targetH; 
          
          // 2. Draw Background Image (Cover)
          const scale = Math.max(canvas.width / img.width, canvas.height / img.height);
          const x = (canvas.width / 2) - (img.width / 2) * scale;
          const y = (canvas.height / 2) - (img.height / 2) * scale;
          ctx.drawImage(img, x, y, img.width * scale, img.height * scale);

          // 3. Draw Color Tint Overlay (Standard)
          if (showOverlay) {
              // Base shadow for readability
              ctx.fillStyle = "rgba(0,0,0,0.1)"; 
              ctx.fillRect(0, 0, canvas.width, canvas.height);
          }

          // 3b. Draw Brand Color Overlay (#81aaed @ 50%)
          if (useColorOverlay) {
              ctx.fillStyle = "rgba(129, 170, 237, 0.5)"; 
              ctx.fillRect(0, 0, canvas.width, canvas.height);
          }

          // 4. Draw Logo (Top Left)
          if (showLogo) {
              const logo = new Image();
              logo.crossOrigin = "anonymous";
              logo.src = LOGO_URL;
              logo.onload = () => {
                  const logoW = canvas.width * 0.3; // Responsive width 30%
                  const maxLogoW = 300;
                  const finalLogoW = Math.min(logoW, maxLogoW);
                  const logoH = (logo.height / logo.width) * finalLogoW;
                  ctx.drawImage(logo, 40, 40, finalLogoW, logoH);
                  // Update preview state after logo loads
                  setPreviewDataUrl(canvas.toDataURL());
              };
          }

          // 5. Draw Headline Text
          if (headline) {
              ctx.save();
              const fontSize = canvas.width * 0.055; // Responsive font size
              ctx.font = `900 ${fontSize}px Montserrat`;
              
              // Calculate Position
              let textX = 60; // Margin
              let textY = canvas.height - 100; // Default bottom

              if (textYAnchor === 'top') textY = 250;
              if (textYAnchor === 'middle') textY = canvas.height / 2;
              
              // Apply Manual Nudges
              textX += textPos.x * 5;
              textY += textPos.y * 5;

              // WORD WRAP LOGIC
              const safeWidth = canvas.width - 120; // 60px padding per side
              const rawPars = headline.split('\n');
              let lines: string[] = [];

              rawPars.forEach(par => {
                  const words = par.split(' ');
                  let currentLine = words[0];
                  
                  for (let i = 1; i < words.length; i++) {
                      const word = words[i];
                      const width = ctx.measureText(currentLine + " " + word).width;
                      if (width < safeWidth) {
                          currentLine += " " + word;
                      } else {
                          lines.push(currentLine);
                          currentLine = word;
                      }
                  }
                  if (currentLine) lines.push(currentLine);
              });
              // -----------------------

              const lineHeight = fontSize * 1.2;
              
              // Measure Text for Box
              const maxWidth = lines.reduce((max, line) => Math.max(max, ctx.measureText(line).width), 0);
              const totalHeight = lines.length * lineHeight;
              
              // Adjust Y for multiline to prevent clipping at bottom
              if (textYAnchor === 'bottom' && lines.length > 1) {
                  textY -= (lines.length - 1) * lineHeight;
              }
              if (textYAnchor === 'middle' && lines.length > 1) {
                  textY -= ((lines.length - 1) * lineHeight) / 2;
              }
              
              ctx.fillStyle = "rgba(15, 30, 61, 0.85)"; // Navy background
              
              // Box Alignment
              let boxX = textX - 20;
              if (textAlign === 'center') boxX = (canvas.width - maxWidth) / 2 - 20;
              if (textAlign === 'right') boxX = canvas.width - maxWidth - 60 - 20;

              let boxY = textY - fontSize + 15; 
              
              ctx.roundRect(boxX, boxY, maxWidth + 40, totalHeight + 20, 16);
              ctx.fill();

              // Draw Text
              ctx.fillStyle = "white";
              ctx.textAlign = textAlign;
              
              let drawX = textX;
              if (textAlign === 'center') drawX = canvas.width / 2;
              if (textAlign === 'right') drawX = canvas.width - 60;

              lines.forEach((line, i) => {
                  ctx.fillText(line, drawX, textY + (i * lineHeight));
              });

              ctx.restore();
          }

          // Update preview state if no logo (otherwise logo onload handles it)
          if (!showLogo) {
            setPreviewDataUrl(canvas.toDataURL());
          }
      };
  };

  // --- ACTIONS ---

  const handleDownload = () => {
      if (activeTab === 'video-gen' && videoUrl) {
          const link = document.createElement('a');
          link.href = videoUrl;
          link.download = `veri_video_${Date.now()}.mp4`;
          link.target = "_blank";
          link.click();
      } else if (canvasRef.current) {
          const link = document.createElement('a');
          link.download = `veri_asset_${Date.now()}.png`;
          link.href = canvasRef.current.toDataURL();
          link.click();
      }
  };

  const handleReset = () => {
      if(window.confirm("Reset all fields?")) {
          setPrompt("");
          setHeadline("");
          setCaption("");
          setImage(null);
          setVideoUrl(null);
          setPreviewDataUrl(null);
          setFeedbackStatus('none');
      }
  };

  const fixGrammar = async () => {
      await checkApiKey();
      if (!headline || !process.env.API_KEY) return;
      try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
          const result = await ai.models.generateContent({
              model: 'gemini-2.5-flash',
              contents: { parts: [{ text: `Fix spelling and grammar to Australian English standards (e.g. 'colour', 'organise', 'program'). Keep it punchy (max 8 words). Return ONLY the corrected text: "${headline}"` }] }
          });
          if (result.text) setHeadline(result.text.trim());
      } catch (e) { handleApiError(e, "Grammar fix failed."); }
  };

  const auditVoice = async () => {
    await checkApiKey();
    if (!caption || !process.env.API_KEY) return;
    setLoading(true);
    try {
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        const result = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: { parts: [{ text: `
              Audit this caption against the Veri Brand Persona (Confident, Intelligent, Human-Centric, Professional, Not Robotic).
              Ensure Australian English spelling/grammar is used (e.g. 'colour', 'optimise').
              
              Strategy Context: ${getStrategy().substring(0, 500)}
              Caption to Audit: "${caption}"

              Output strict JSON:
              {
                "score": number (0-100),
                "critique": "Short actionable advice (max 1 sentence) on how to improve tone."
              }
            ` }] }
        });
        
        const txt = result.text?.replace(/```json|```/g, '').trim();
        if (txt) {
            const data = JSON.parse(txt);
            setVoiceScore(data.score);
            setVoiceCritique(data.critique);
        }
    } catch (e) {
        handleApiError(e, "Audit failed.");
    } finally {
        setLoading(false);
    }
  };

  const generateSocialCaption = async () => {
      await checkApiKey();
      if (!process.env.API_KEY) return;
      setLoading(true);
      setVoiceScore(null); // Reset audit
      try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
          const result = await ai.models.generateContent({
              model: 'gemini-2.5-flash',
              contents: { parts: [{ text: `
                Act as a Senior Social Media Manager for app.microcredentials.io.
                Write a compelling social media caption (LinkedIn/Twitter style) for a post.
                
                Visual Description: ${prompt}
                Headline Overlay: ${headline}
                Brand Strategy Context: ${getStrategy().substring(0, 1000)}
                ${getUserPreferences()}
                
                Requirements:
                1. Hook the reader immediately.
                2. Provide value or insight related to verifiable credentials/blockchain/education.
                3. Tone: Professional, confident, forward-thinking (Veri persona).
                4. Language: Australian English (e.g. 'program', 'optimise', 'centre', 'colour').
                5. Structure: concise paragraphs, use emojis sparingly if appropriate for professional context.
                6. CRITICAL: END WITH 3-5 RELEVANT HASHTAGS (e.g., #Microcredentials #EdTech).
                7. Total length: Under 150 words.
              ` }] }
          });
          if (result.text) setCaption(result.text.trim());
      } catch (e) { 
          handleApiError(e, "Caption generation failed.");
      } finally {
          setLoading(false);
      }
  };

  const loadOfficialAsset = async (url: string) => {
      setLoading(true);
      try {
          const response = await fetch(url);
          const blob = await response.blob();
          const reader = new FileReader();
          reader.onloadend = () => {
              setImage(reader.result as string);
              setLoading(false);
          };
          reader.readAsDataURL(blob);
      } catch (e) {
          console.error(e);
          setLoading(false);
      }
  };

  // --- GENERATION ---

  const generateImage = async () => {
      await checkApiKey();
      if (!process.env.API_KEY) return;
      setLoading(true);
      setFeedbackStatus('none');
      setStatusMsg("Consulting brand strategy & generating visual...");
      
      try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
          let imageBlob = "";
          const imgConfig = { aspectRatio: aspectRatio };

          const basePromptContext = `
            Context: ${getStrategy().substring(0, 500)}. 
            ${getUserPreferences()}
          `;

          if (useVeri) {
             const ref = await fetchReferenceImage();
             const refData = ref.split(',')[1];
             const resp = await ai.models.generateContent({
                 model: 'gemini-2.5-flash-image',
                 contents: { parts: [
                     { inlineData: { mimeType: 'image/jpeg', data: refData } },
                     { text: `Character Reference: Use the woman in this image (Veri). 
                     Generate a photorealistic corporate shot of her: ${prompt}. 
                     ${basePromptContext}
                     Style: High-end, navy/blue tones, soft lighting. Aspect Ratio: ${aspectRatio}.` }
                 ]},
                 config: { imageConfig: imgConfig }
             });
             const part = resp.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
             if (part?.inlineData) imageBlob = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          } else {
              // Strict Brand Fallback
              const strictPrompt = `
              Generate a photorealistic corporate image: ${prompt}. 
              ${basePromptContext}
              Style Rules: 
              1. Photorealistic rendering ONLY (No cartoons/illustrations).
              2. Lighting: Soft, confident, professional studio lighting.
              3. Palette: Dominated by Navy Blue (#0F1E3D), White, and touches of Electric Blue.
              4. Wardrobe: Professional textured fabrics, suits, blazers.
              5. Aspect Ratio: ${aspectRatio}.
              `;

              const resp = await ai.models.generateContent({
                  model: 'gemini-2.5-flash-image',
                  contents: { parts: [{ text: strictPrompt }] },
                  config: { imageConfig: imgConfig }
              });
              const part = resp.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
              if (part?.inlineData) imageBlob = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          }

          if (imageBlob) setImage(imageBlob);

      } catch (e) {
          handleApiError(e, "Image generation failed. Check Quota/API Key.");
      } finally {
          setLoading(false);
      }
  };

  const refineImage = async () => {
      await checkApiKey();
      if (!process.env.API_KEY || !image) return;
      setLoading(true);
      setFeedbackStatus('none');
      setStatusMsg("Refining current asset based on instructions...");
      
      try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
          
          // Get current image data
          const imageData = image.split(',')[1];
          const imgConfig = { aspectRatio: aspectRatio };

          const refinePrompt = `
             EDIT INSTRUCTIONS: The user wants to modify the provided image.
             User Instruction: "${prompt}"
             
             Constraints:
             1. Maintain the current composition and character as much as possible, unless explicitly asked to change.
             2. Keep photorealistic professional quality.
             3. Adhere to Australian English if text is involved.
             4. ${getUserPreferences()}
          `;

          const resp = await ai.models.generateContent({
              model: 'gemini-2.5-flash-image',
              contents: { parts: [
                  { inlineData: { mimeType: 'image/jpeg', data: imageData } },
                  { text: refinePrompt }
              ]},
              config: { imageConfig: imgConfig }
          });
          
          const part = resp.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
          if (part?.inlineData) setImage(`data:${part.inlineData.mimeType};base64,${part.inlineData.data}`);

      } catch (e) {
          handleApiError(e, "Refinement failed.");
      } finally {
          setLoading(false);
      }
  };

  const generateRemix = async () => {
      await checkApiKey();
      if (!process.env.API_KEY || !remixImage) return;
      setLoading(true);
      setFeedbackStatus('none');
      setStatusMsg("Remixing scene with Veri...");
      
      try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
          
          // Get Veri Ref
          const veriRef = await fetchReferenceImage();
          const veriData = veriRef.split(',')[1];
          const sceneData = remixImage.split(',')[1];

          const resp = await ai.models.generateContent({
              model: 'gemini-2.5-flash-image',
              contents: { parts: [
                  { inlineData: { mimeType: 'image/jpeg', data: veriData } },
                  { inlineData: { mimeType: 'image/jpeg', data: sceneData } },
                  { text: `
                    Image 1 is the Character Reference (Veri).
                    Image 2 is the Composition Reference (Scene/Pose).
                    Task: Recreate the scene in Image 2 but replace the main subject with Veri from Image 1.
                    Maintain the pose, lighting direction, and environment of Image 2.
                    ${getUserPreferences()}
                    Ensure the result is photorealistic and matches the brand navy/blue aesthetic.
                  ` }
              ]},
              config: { imageConfig: { aspectRatio: aspectRatio } }
          });
          
          const part = resp.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
          if (part?.inlineData) setImage(`data:${part.inlineData.mimeType};base64,${part.inlineData.data}`);

      } catch (e) {
          handleApiError(e, "Remix failed.");
      } finally {
          setLoading(false);
      }
  };

  const generateVideo = async () => {
      await checkApiKey();

      setLoading(true);
      setFeedbackStatus('none');
      setStatusMsg("Initializing Veo Model...");
      
      try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
          setStatusMsg("Veo is dreaming (this takes ~1 min)...");
          
          let videoRatio = '16:9';
          if (aspectRatio === '3:4') videoRatio = '9:16';
          
          let operation = await ai.models.generateVideos({
              model: 'veo-3.1-fast-generate-preview',
              prompt: `Cinematic corporate video, stable camera. ${prompt}. Professional lighting, navy and blue tones. ${getUserPreferences()}`,
              config: {
                  numberOfVideos: 1,
                  resolution: '1080p',
                  aspectRatio: videoRatio
              }
          });

          while (!operation.done) {
              await new Promise(r => setTimeout(r, 5000));
              setStatusMsg("Rendering frames...");
              operation = await ai.operations.getVideosOperation({ operation });
          }

          const videoUri = operation.response?.generatedVideos?.[0]?.video?.uri;
          if (videoUri) {
               setVideoUrl(`${videoUri}&key=${process.env.API_KEY}`);
          }

      } catch (e) {
          handleApiError(e, "Video generation failed.");
      } finally {
          setLoading(false);
      }
  };

  // Helper to determine if we should show generation controls
  const showControls = activeTab === 'image-gen' || activeTab === 'video-gen' || (activeTab === 'upload' && image);

  return (
    <div className="px-4 md:px-[70px] py-[70px] bg-gradient-to-b from-white to-soft-blue/30">
      <h2 className="font-extrabold text-3xl md:text-4xl text-navy border-l-[7px] border-electric-blue pl-6 mb-[60px]">
        04. AI Asset Engine
      </h2>

      <div className="bg-white rounded-[20px] shadow-2xl overflow-hidden flex flex-col lg:flex-row min-h-[700px]">
        
        {/* LEFT PANEL: CONTROLS */}
        <div className="w-full lg:w-[450px] bg-navy flex flex-col text-white max-h-[900px]">
            
            {/* Fixed Header */}
            <div className="p-6 md:p-8 pb-4 bg-navy z-10 shadow-sm shrink-0">
                <div className="flex bg-white/10 p-1 rounded-xl overflow-x-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:'none'] [scrollbar-width:'none']">
                    <button onClick={() => setActiveTab('upload')} className={`flex-1 min-w-[80px] py-2 rounded-lg text-xs font-bold flex flex-col items-center justify-center gap-1 transition-all ${activeTab === 'upload' ? 'bg-electric-blue text-white' : 'text-white/50 hover:text-white'}`}>
                        <Upload size={14} /> Upload
                    </button>
                    <button onClick={() => setActiveTab('image-gen')} className={`flex-1 min-w-[80px] py-2 rounded-lg text-xs font-bold flex flex-col items-center justify-center gap-1 transition-all ${activeTab === 'image-gen' ? 'bg-electric-blue text-white' : 'text-white/50 hover:text-white'}`}>
                        <ImageIcon size={14} /> Create
                    </button>
                    <button onClick={() => setActiveTab('remix')} className={`flex-1 min-w-[80px] py-2 rounded-lg text-xs font-bold flex flex-col items-center justify-center gap-1 transition-all ${activeTab === 'remix' ? 'bg-electric-blue text-white' : 'text-white/50 hover:text-white'}`}>
                        <RefreshCw size={14} /> Remix
                    </button>
                    <button onClick={() => setActiveTab('video-gen')} className={`flex-1 min-w-[80px] py-2 rounded-lg text-xs font-bold flex flex-col items-center justify-center gap-1 transition-all ${activeTab === 'video-gen' ? 'bg-electric-blue text-white' : 'text-white/50 hover:text-white'}`}>
                        <Video size={14} /> Veo
                    </button>
                </div>
            </div>

            {/* Scrollable Content */}
            <div className="p-6 md:p-8 pt-0 flex-1 overflow-y-auto flex flex-col gap-6">

                {/* Content Controls */}
                {activeTab === 'upload' && (
                    <div className="space-y-4">
                        <div className="border-2 border-dashed border-white/20 rounded-xl h-32 flex flex-col items-center justify-center hover:bg-white/5 cursor-pointer" onClick={() => fileInputRef.current?.click()}>
                            <Upload className="mb-2 text-electric-blue"/>
                            <span className="text-sm font-bold">Click to Upload Image</span>
                            <input type="file" ref={fileInputRef} className="hidden" accept="image/*" onChange={(e) => {
                                const file = e.target.files?.[0];
                                if (file) {
                                    const reader = new FileReader();
                                    reader.onload = (evt) => setImage(evt.target?.result as string);
                                    reader.readAsDataURL(file);
                                }
                            }}/>
                        </div>
                        {!image && (
                            <>
                                <p className="text-center text-xs text-white/40 uppercase font-bold tracking-widest">OR Select Official Asset</p>
                                <div className="grid grid-cols-2 gap-2">
                                    {OFFICIAL_ASSETS.map((asset) => (
                                        <button 
                                            key={asset.name} 
                                            onClick={() => loadOfficialAsset(asset.url)}
                                            className="bg-white/5 hover:bg-white/10 p-2 rounded-lg flex flex-col items-center gap-2 text-xs transition-colors"
                                        >
                                            <img src={asset.url} className="h-16 w-full object-cover rounded" />
                                            {asset.name}
                                        </button>
                                    ))}
                                </div>
                            </>
                        )}
                    </div>
                )}

                {activeTab === 'remix' && (
                    <div className="space-y-4">
                        <div className="border-2 border-dashed border-white/20 rounded-xl h-32 flex flex-col items-center justify-center hover:bg-white/5 cursor-pointer" onClick={() => remixInputRef.current?.click()}>
                            {remixImage ? (
                                <img src={remixImage} className="h-full w-full object-cover rounded-xl opacity-60" />
                            ) : (
                                <>
                                    <Upload className="mb-2 text-electric-blue"/>
                                    <span className="text-sm font-bold">Upload Scene Reference</span>
                                </>
                            )}
                            <input type="file" ref={remixInputRef} className="hidden" accept="image/*" onChange={(e) => {
                                const file = e.target.files?.[0];
                                if (file) {
                                    const reader = new FileReader();
                                    reader.onload = (evt) => setRemixImage(evt.target?.result as string);
                                    reader.readAsDataURL(file);
                                }
                            }}/>
                        </div>
                        <button 
                            onClick={generateRemix}
                            disabled={loading || !remixImage}
                            className={`w-full py-3 rounded-xl font-bold text-lg flex items-center justify-center gap-2 transition-all ${loading || !remixImage ? 'bg-white/10 cursor-not-allowed' : 'bg-electric-blue hover:bg-[#00d4ff]'}`}
                        >
                            {loading ? <RefreshCw className="animate-spin"/> : <Wand2 />} Remix with Veri
                        </button>
                    </div>
                )}

                {/* GENERATION / EDITING CONTROLS (Rendered in Upload mode too if image exists) */}
                {showControls && (
                    <div className="space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">
                        <div className="flex items-center justify-between">
                            <label className="text-xs font-bold text-gold uppercase">Format</label>
                            {activeTab === 'image-gen' && (
                                <label className="flex items-center gap-2 cursor-pointer bg-black/20 px-2 py-1 rounded">
                                    <input type="checkbox" checked={useVeri} onChange={e => setUseVeri(e.target.checked)} className="accent-electric-blue w-4 h-4" />
                                    <span className="text-xs text-white font-bold">Use Veri Character</span>
                                </label>
                            )}
                        </div>
                        
                        {/* Aspect Ratio Selector */}
                        <div className="flex bg-white/10 rounded-lg p-1 gap-1">
                            <button 
                                onClick={() => setAspectRatio('1:1')} 
                                className={`flex-1 py-2 rounded-md flex items-center justify-center gap-2 text-xs font-bold transition-colors ${aspectRatio === '1:1' ? 'bg-electric-blue text-white' : 'text-white/50 hover:bg-white/5'}`}
                                title="Square (1:1)"
                            >
                                <Square size={14}/> 1:1
                            </button>
                            <button 
                                onClick={() => setAspectRatio('3:4')} 
                                className={`flex-1 py-2 rounded-md flex items-center justify-center gap-2 text-xs font-bold transition-colors ${aspectRatio === '3:4' ? 'bg-electric-blue text-white' : 'text-white/50 hover:bg-white/5'}`}
                                title="Portrait (3:4)"
                            >
                                <RectangleVertical size={14}/> 3:4
                            </button>
                            <button 
                                onClick={() => setAspectRatio('16:9')} 
                                className={`flex-1 py-2 rounded-md flex items-center justify-center gap-2 text-xs font-bold transition-colors ${aspectRatio === '16:9' ? 'bg-electric-blue text-white' : 'text-white/50 hover:bg-white/5'}`}
                                title="Landscape (16:9)"
                            >
                                <RectangleHorizontal size={14}/> 16:9
                            </button>
                        </div>

                        <div className="space-y-2">
                            <div className="flex justify-between">
                                <label className="text-xs font-bold text-white/70">PROMPT</label>
                                <label className="flex items-center gap-1 cursor-pointer">
                                    <input type="checkbox" checked={useColorOverlay} onChange={e => setUseColorOverlay(e.target.checked)} className="accent-electric-blue" />
                                    <span className="text-[10px] text-electric-blue font-bold">Brand Tint (#81aaed)</span>
                                </label>
                            </div>
                            <textarea 
                                value={prompt} 
                                onChange={e => setPrompt(e.target.value)} 
                                placeholder={activeTab === 'video-gen' ? "Cinematic movement..." : "Describe the scene or edits..."}
                                className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-sm h-24 resize-none focus:border-electric-blue outline-none"
                            />
                            <div className="flex justify-end">
                                <button onClick={handleReset} className="text-[10px] text-red-400 hover:text-red-300">Reset All</button>
                            </div>
                        </div>

                        <div className="flex gap-2">
                            {/* GENERATE BUTTON - Visible in Create/Video mode OR if no image is present */}
                            {(activeTab === 'image-gen' || activeTab === 'video-gen') && (
                                <button 
                                    onClick={activeTab === 'image-gen' ? generateImage : generateVideo}
                                    disabled={loading || !prompt}
                                    className={`flex-1 py-3 rounded-xl font-bold text-lg flex items-center justify-center gap-2 transition-all ${loading ? 'bg-white/10 cursor-wait' : 'bg-electric-blue hover:bg-[#00d4ff] shadow-lg'}`}
                                >
                                    {loading ? <RefreshCw className="animate-spin"/> : <Wand2 />}
                                    {loading ? "Generating..." : (activeTab === 'video-gen' ? "Generate Video" : "Generate New")}
                                </button>
                            )}
                            
                            {/* REFINE BUTTON - Visible if image exists (Any mode except Video) */}
                            {(image && !loading && activeTab !== 'video-gen') && (
                                <button 
                                    onClick={refineImage}
                                    title="Refine current image with prompt"
                                    className={`flex-1 py-3 rounded-xl font-bold text-lg flex items-center justify-center gap-2 transition-all border border-white/20 ${activeTab === 'upload' ? 'bg-electric-blue hover:bg-[#00d4ff] text-white shadow-lg' : 'bg-white/10 hover:bg-white/20 text-white'}`}
                                >
                                    <Pencil size={20} />
                                    Refine / Edit
                                </button>
                            )}
                        </div>
                        
                        {loading && <p className="text-center text-xs text-white/60 animate-pulse">{statusMsg}</p>}
                    </div>
                )}

                <hr className="border-white/10 my-2" />

                {/* TEXT & OVERLAY CONTROLS */}
                <div className="space-y-4">
                    <div className="flex justify-between items-center">
                        <h4 className="font-bold text-electric-blue flex items-center gap-2"><Layers size={16}/> Overlay Controls</h4>
                        <div className="flex gap-2">
                            <button onClick={() => setShowLogo(!showLogo)} className={`text-[10px] px-2 py-1 rounded border ${showLogo ? 'bg-white text-navy' : 'border-white/40 text-white/50'}`}>Logo</button>
                            <button onClick={() => setShowOverlay(!showOverlay)} className={`text-[10px] px-2 py-1 rounded border ${showOverlay ? 'bg-white text-navy' : 'border-white/40 text-white/50'}`}>Tint</button>
                        </div>
                    </div>

                    {/* Headline Input */}
                    <div>
                        <div className="flex justify-between items-center mb-1">
                            <label className="text-xs font-bold text-gold uppercase">Headline Text</label>
                            <button onClick={fixGrammar} className="text-[10px] bg-white/10 hover:bg-white/20 px-2 py-1 rounded flex items-center gap-1 transition-colors"><Sparkles size={10}/> Fix Grammar (AU)</button>
                        </div>
                        <textarea 
                            value={headline} 
                            onChange={e => setHeadline(e.target.value)} 
                            className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-sm h-20 resize-none focus:border-electric-blue outline-none font-heading font-bold"
                            placeholder="ENTER HEADLINE..."
                        />
                    </div>

                    {/* Position Controls */}
                    <div className="grid grid-cols-2 gap-4">
                        <div>
                            <label className="text-[10px] uppercase text-white/50 mb-1 block">Alignment</label>
                            <div className="flex bg-white/10 rounded-md p-1">
                                {['left', 'center', 'right'].map((a) => (
                                    <button key={a} onClick={() => setTextAlign(a as any)} className={`flex-1 py-1 rounded text-xs ${textAlign === a ? 'bg-electric-blue' : ''}`}>{a.charAt(0).toUpperCase()}</button>
                                ))}
                            </div>
                        </div>
                        <div>
                            <label className="text-[10px] uppercase text-white/50 mb-1 block">Vertical</label>
                            <div className="flex bg-white/10 rounded-md p-1">
                                {['top', 'middle', 'bottom'].map((a) => (
                                    <button key={a} onClick={() => setTextYAnchor(a as any)} className={`flex-1 py-1 rounded text-xs ${textYAnchor === a ? 'bg-electric-blue' : ''}`}>{a.charAt(0).toUpperCase()}</button>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Nudge Sliders */}
                    <div>
                        <label className="text-[10px] uppercase text-white/50 mb-1 block flex items-center gap-1"><Move size={10}/> Manual Nudge</label>
                        <div className="flex gap-2 items-center">
                            <span className="text-xs w-4">X</span>
                            <input type="range" min="-20" max="20" value={textPos.x} onChange={e => setTextPos({...textPos, x: parseInt(e.target.value)})} className="flex-1 h-1 bg-white/20 rounded-lg appearance-none cursor-pointer" />
                        </div>
                        <div className="flex gap-2 items-center mt-2">
                            <span className="text-xs w-4">Y</span>
                            <input type="range" min="-20" max="20" value={textPos.y} onChange={e => setTextPos({...textPos, y: parseInt(e.target.value)})} className="flex-1 h-1 bg-white/20 rounded-lg appearance-none cursor-pointer" />
                        </div>
                    </div>
                </div>
                
                <hr className="border-white/10 my-2" />

                {/* SOCIAL CAPTION SECTION */}
                <div className="space-y-2">
                    <div className="flex justify-between items-center">
                        <h4 className="font-bold text-electric-blue flex items-center gap-2 text-sm"><FileText size={16}/> Social Caption</h4>
                        <div className="flex gap-1">
                            <button onClick={auditVoice} disabled={loading || !caption} className="text-[10px] bg-white/10 hover:bg-white/20 text-white px-2 py-1 rounded flex items-center gap-1 transition-colors border border-white/20">
                                <ShieldCheck size={10}/> Audit Tone
                            </button>
                            <button onClick={generateSocialCaption} disabled={loading || !prompt} className="text-[10px] bg-electric-blue hover:bg-[#00d4ff] text-white px-2 py-1 rounded flex items-center gap-1 transition-colors">
                                <Sparkles size={10}/> AI Write (AU)
                            </button>
                        </div>
                    </div>
                    
                    {voiceScore !== null && (
                        <div className={`p-2 rounded border text-xs ${voiceScore > 80 ? 'bg-green-500/20 border-green-500/50 text-green-200' : 'bg-orange-500/20 border-orange-500/50 text-orange-200'}`}>
                            <div className="flex justify-between font-bold mb-1">
                                <span>Veri Voice Score: {voiceScore}%</span>
                            </div>
                            <p className="opacity-80 leading-tight">{voiceCritique}</p>
                        </div>
                    )}

                    <div className="relative group">
                        <textarea 
                            value={caption} 
                            onChange={e => setCaption(e.target.value)} 
                            className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-xs h-24 resize-none focus:border-electric-blue outline-none text-white/90 font-sans leading-relaxed"
                            placeholder="AI generated caption with hashtags will appear here..."
                        />
                        {caption && (
                            <button 
                                onClick={() => {
                                    navigator.clipboard.writeText(caption);
                                    alert("Caption copied to clipboard!");
                                }}
                                className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 p-1.5 rounded-md text-white transition-colors opacity-0 group-hover:opacity-100"
                                title="Copy Caption"
                            >
                                <Copy size={14} />
                            </button>
                        )}
                    </div>
                </div>
                
                <button onClick={handleDownload} disabled={(!image && !videoUrl)} className="mt-auto bg-green-500 hover:bg-green-600 text-white py-4 rounded-xl font-bold shadow-lg flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed">
                    <Download size={20}/> Download Final Asset
                </button>

            </div>

        </div>

        {/* RIGHT PANEL: CANVAS / PREVIEW */}
        <div className="flex-1 bg-gray-100 relative flex flex-col items-center p-8 min-h-[500px]">
            {/* Background Pattern */}
            <div className="absolute inset-0 opacity-5 bg-[radial-gradient(#0F1E3D_1px,transparent_1px)] [background-size:16px_16px] pointer-events-none"></div>

            {/* View Mode Toggle */}
            <div className="relative z-10 flex gap-2 bg-white p-1 rounded-lg shadow-sm mb-6">
                <button onClick={() => setPreviewMode('editor')} className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-bold transition-all ${previewMode === 'editor' ? 'bg-navy text-white' : 'text-gray-500 hover:bg-gray-100'}`}>
                    <Monitor size={14} /> Editor
                </button>
                <button onClick={() => setPreviewMode('linkedin')} className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-bold transition-all ${previewMode === 'linkedin' ? 'bg-[#0077b5] text-white' : 'text-gray-500 hover:bg-gray-100'}`}>
                    <Linkedin size={14} /> LinkedIn
                </button>
                <button onClick={() => setPreviewMode('facebook')} className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-bold transition-all ${previewMode === 'facebook' ? 'bg-[#1877F2] text-white' : 'text-gray-500 hover:bg-gray-100'}`}>
                    <Facebook size={14} /> Facebook
                </button>
                <button onClick={() => setPreviewMode('instagram')} className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-bold transition-all ${previewMode === 'instagram' ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white' : 'text-gray-500 hover:bg-gray-100'}`}>
                    <Smartphone size={14} /> Instagram
                </button>
            </div>

            {/* Preview Container */}
            <div className="relative z-10 flex flex-col items-center w-full">
                {activeTab === 'video-gen' && videoUrl ? (
                    <div className={`relative shadow-2xl rounded-xl overflow-hidden bg-black ${aspectRatio === '3:4' ? 'max-w-[340px] aspect-[9/16]' : 'max-w-[600px] aspect-video'}`}>
                        <video src={videoUrl} controls className="w-full h-full object-cover" />
                        {showOverlay && <div className="absolute inset-0 bg-electric-blue/20 pointer-events-none"></div>}
                        {showLogo && <img src={LOGO_URL} className="absolute top-4 left-4 w-20 opacity-90" />}
                    </div>
                ) : (
                    // Canvas / Image Container
                    <div className="relative">
                        {!image ? (
                            <div className="w-[400px] h-[400px] bg-white rounded-xl shadow-lg border-2 border-dashed border-gray-300 flex flex-col items-center justify-center text-gray-400">
                                <ImageIcon size={64} className="mb-4 opacity-50"/>
                                <p className="font-bold">Preview Area</p>
                                <p className="text-sm">Generate or Upload to start</p>
                                {loading && (
                                    <div className="mt-4 flex flex-col items-center">
                                        <div className="w-6 h-6 border-2 border-electric-blue border-t-transparent rounded-full animate-spin"></div>
                                        <span className="text-xs text-electric-blue mt-2">Auto-generating...</span>
                                    </div>
                                )}
                            </div>
                        ) : (
                            <>
                                {/* EDITOR MODE - ALWAYS RENDERED TO MAINTAIN REF, HIDDEN WHEN NOT ACTIVE */}
                                <div className={`relative shadow-2xl rounded-sm overflow-hidden border-8 border-white bg-white ${previewMode === 'editor' ? 'block' : 'hidden'}`}>
                                     <canvas 
                                        ref={canvasRef} 
                                        style={{ 
                                            width: '100%', 
                                            maxHeight: '65vh',
                                            maxWidth: aspectRatio === '16:9' ? '700px' : '500px'
                                        }} 
                                        className="block"
                                    />
                                </div>

                                {/* LINKEDIN MODE */}
                                {previewMode === 'linkedin' && (
                                    <div className="w-[500px] bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden font-sans text-left">
                                        <div className="p-4 flex gap-3">
                                            <div className="w-12 h-12 bg-navy rounded-full"></div>
                                            <div>
                                                <div className="font-bold text-sm text-gray-900">app.microcredentials.io</div>
                                                <div className="text-xs text-gray-500">10,243 followers • 2h • <span className="text-gray-400">🌐</span></div>
                                            </div>
                                        </div>
                                        <div className="px-4 pb-2 text-sm text-gray-800 whitespace-pre-wrap">{caption || "Your engaging caption will appear here..."}</div>
                                        {/* Use previewDataUrl if available (for overlay burn-in), fallback to raw image */}
                                        <img src={previewDataUrl || image} className="w-full border-t border-b border-gray-100" />
                                        <div className="p-3 border-t border-gray-100 bg-gray-50 flex justify-between text-gray-500 text-sm font-bold">
                                            <span>Like</span><span>Comment</span><span>Share</span><span>Send</span>
                                        </div>
                                    </div>
                                )}
                                
                                {/* FACEBOOK MODE */}
                                {previewMode === 'facebook' && (
                                    <div className="w-[500px] bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden font-sans text-left">
                                        <div className="p-3 flex justify-between items-center">
                                            <div className="flex gap-2">
                                                <div className="w-10 h-10 bg-navy rounded-full"></div>
                                                <div>
                                                    <div className="font-bold text-sm text-gray-900 leading-tight">app.microcredentials.io</div>
                                                    <div className="text-xs text-gray-500 flex items-center gap-1">2h • <span className="text-gray-400">🌐</span></div>
                                                </div>
                                            </div>
                                            <span className="text-gray-500">•••</span>
                                        </div>
                                        <div className="px-3 pb-2 text-sm text-gray-800 whitespace-pre-wrap">{caption || "Your engaging caption will appear here..."}</div>
                                        {/* Use previewDataUrl if available (for overlay burn-in), fallback to raw image */}
                                        <img src={previewDataUrl || image} className="w-full" />
                                        <div className="px-4 py-2 bg-gray-50 border-t border-gray-200">
                                            <div className="text-xs text-gray-500 font-bold uppercase">MICROCREDENTIALS.IO</div>
                                            <div className="font-bold text-sm text-gray-900 truncate">{headline || "The Architect of Potential"}</div>
                                        </div>
                                        <div className="p-2 border-t border-gray-100 flex justify-between text-gray-500 text-sm font-bold px-8">
                                            <span>Like</span><span>Comment</span><span>Share</span>
                                        </div>
                                    </div>
                                )}

                                {/* INSTAGRAM MODE */}
                                {previewMode === 'instagram' && (
                                    <div className="w-[380px] bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden font-sans text-left mx-auto">
                                        <div className="p-3 flex items-center justify-between border-b border-gray-100">
                                            <div className="flex items-center gap-2">
                                                 <div className="w-8 h-8 bg-gradient-to-tr from-yellow-400 to-purple-600 p-[2px] rounded-full">
                                                    <div className="bg-white w-full h-full rounded-full border-2 border-white"></div>
                                                 </div>
                                                 <span className="font-bold text-sm">microcredentials.io</span>
                                            </div>
                                            <span className="text-gray-800">•••</span>
                                        </div>
                                        {/* Use previewDataUrl if available (for overlay burn-in), fallback to raw image */}
                                        <img src={previewDataUrl || image} className="w-full" />
                                        <div className="p-3">
                                            <div className="flex justify-between mb-2 text-gray-800">
                                                <div className="flex gap-4">
                                                    <span className="font-bold">♡</span>
                                                    <span className="font-bold">💬</span>
                                                    <span className="font-bold">✈️</span>
                                                </div>
                                                <span className="font-bold">⚑</span>
                                            </div>
                                            <div className="text-sm font-bold mb-1">2,491 likes</div>
                                            <div className="text-sm">
                                                <span className="font-bold mr-2">microcredentials.io</span>
                                                <span className="text-gray-800">{caption ? caption.substring(0, 80) + "..." : "Caption preview..."}</span>
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </>
                        )}
                    </div>
                )}
                
                {/* LIKE / DISLIKE FEEDBACK CONTROLS */}
                {(image || videoUrl) && (
                    <div className="mt-6 flex gap-4 bg-white p-2 rounded-full shadow-lg border border-gray-100">
                        <button 
                            onClick={() => handleFeedback('liked')} 
                            className={`p-3 rounded-full transition-all flex items-center gap-2 font-bold ${feedbackStatus === 'liked' ? 'bg-green-100 text-green-600' : 'hover:bg-gray-100 text-gray-500'}`}
                            title="I like this style (Train AI)"
                        >
                            <ThumbsUp size={20} fill={feedbackStatus === 'liked' ? "currentColor" : "none"} />
                            {feedbackStatus === 'liked' && <span className="text-xs">Learned</span>}
                        </button>
                        <div className="w-px bg-gray-200 my-1"></div>
                        <button 
                            onClick={() => handleFeedback('disliked')} 
                            className={`p-3 rounded-full transition-all flex items-center gap-2 font-bold ${feedbackStatus === 'disliked' ? 'bg-red-100 text-red-600' : 'hover:bg-gray-100 text-gray-500'}`}
                            title="I dislike this style (Train AI)"
                        >
                            <ThumbsDown size={20} fill={feedbackStatus === 'disliked' ? "currentColor" : "none"} />
                            {feedbackStatus === 'disliked' && <span className="text-xs">Avoided</span>}
                        </button>
                    </div>
                )}
            </div>
            
            {/* Loading Overlay */}
            {loading && (
                <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center">
                    <div className="w-16 h-16 border-4 border-electric-blue border-t-transparent rounded-full animate-spin mb-4"></div>
                    <h3 className="font-bold text-navy text-xl animate-pulse">{statusMsg || "Processing..."}</h3>
                    <p className="text-navy/50 text-sm mt-2">Consulting Brand Strategy...</p>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default AIGenerator;
